### ISSUE TITLE
Request to include the ability to list multiple primary calibrators

### ISSUE THREAD

**Issue by Sarah-Bradbury** [AlecThomson/quocka#1]
This request is for the ability to list multiple primary calibrators in the template file (e.g., in 'template.cfg': `primary=1934-638,0823-500`) so that the primary calibration stages can be run on all primary calibrators (if multiple exist).
This change would occur in the primary calibration stages located in the 'run_cal.py' script. 
The ability to list multiple calibrators is required in the case where both primary calibrators (1934-638 and 0823-500) are present in the source list (e.g., because the data to be calibrated are from multiple observing runs where different primary calibrators were used). 
This is already functional for the secondary calibrators, so this change would involve copying this existing functionality and applying it for the primary calibrators.

Currently, the code reads:
```python
       for i, source in enumerate(slist):
            frqid = int(source[-4:])
            if frqid != frqb:
                continue
            if prical in source:
                pricalname = source
            elif seccal != "" and any([sc in source for sc in seccal.split(",")]):
                seccalnames.append(source)
            elif seccal_ext in source and seccal_ext != "":
                ext_seccalname = source
            elif polcal != "" and any([pc in source for pc in polcal.split(",")]):
                polcalnames.append(source)
            elif target_ext != "" and any(
                [es in source for es in target_ext.split(",")]
            ):
                ext_targetnames.append(source)
            else:
                targetnames.append(source)
                src_to_plot.append(source[:-5])
```                
To include the ability to list multiple primary calibrators, the code could be changed to e.g.:
```python
       for i, source in enumerate(slist):
            frqid = int(source[-4:])
            if frqid != frqb:
                continue
            if source.split('.')[0] in ['1934-638','0823-500']:
                pricalname = source
            elif seccal != "" and any([sc in source for sc in seccal.split(",")]):
                seccalnames.append(source)
            elif seccal_ext in source and seccal_ext != "":
                ext_seccalname = source
            elif polcal != "" and any([pc in source for pc in polcal.split(",")]):
                polcalnames.append(source)
            elif target_ext != "" and any(
                [es in source for es in target_ext.split(",")]
            ):
                ext_targetnames.append(source)
            else:
                targetnames.append(source)
                src_to_plot.append(source[:-5])
```
                
Thanks!

**Comment by AlecThomson** [comment]
Relevant line is here: https://github.com/AlecThomson/quocka/blob/5818be4d070176a940e177df367c18461a09f19e/quocka/core/run_cal.py#L296

**Comment by AlecThomson** [comment]
There's a few things here that will need a bit more thought. The calibration strategy currently relies on a single primary calibrator - so we'll need some method to determine which cal to choose. Naively, we could just select the primary closest in time to the secondary, but there may be some gotchas there. Tagging @gheald, @tjgalvin, @zhangxiang-planet

**Comment by tjgalvin** [comment]
My immediate thought here is that we might be lucky and not have to worry about this. The `0823-500` source is known to be variable, so it should ideally not be used to establish the absolute flux scale in the same way `1934-638` is capable of doing. Any differences between the observed `0823-500` and its stored model would be absorbed into the bandpass solutions and carried through to the sources you copy the table through to. 

In my experience, `0823-500` is observed when `1934-638` is below the horizon when observing starts and ATCA needs to have its set on online solutions derived (the dcal/pcal/acal steps). It makes sense as well to spend a few moments to observe `0823-500` to get a bandpass solution as a just in case. 

Is the idea here simply to use a set of better bandpass solutions that are closer in time to the source? Was this perhaps prompted by some bad `1934-638` solution?

**Comment by gheald** [comment]
Noting that the observing strategy was just as @tjgalvin describes - i.e. `0823-500` only used when `1934-638` not high enough for setup purposes, but not intended to be used for primary calibration unless there are extenuating circumstances.

However I can imagine cases where we didn't get `1934-638` as planned for some reason, and then I would think bootstrapping `0823-500` from another observation (close on the calendar) would be useful to avoid the variability aspect.

**Comment by zhangxiang-planet** [comment]
In our previous QUOCKA data processing, only `1934-638` has been used as the primary calibrator. As @tjgalvin and @gheald point out, we've considered using `0823-500` only because a stupid observer (aka me) forgot to observe `1934-638` during one night, while `0823-500` was observed that night... 

However, after a few calibrating tests, we confirmed that `1934-638` was obviously the better flux calibrator, and we decided to use part of the set up observation on `1934-638` as the primary calibrator observation.

**Comment by AlecThomson** [comment]
Thanks for the discussion, all! This makes a lot of sense.

For now @Sarah-Bradbury, I think we should continue using `1934-638` (if available) and only use 0823 if its not available.
